<?php
// Ensure no output before this script
ob_start(); // Start output buffering
include_once("../config/config.php");
include_once(DIR_URL . "/db/dbConnection.php");
    

$searching_name1 = $_SESSION['searching_name'] ?? ''; // Get field name from session or set as empty
// echo "export  = ".$searching_name1;
$table_name1 = $_SESSION['table_name'];
$field_name1 = $_SESSION['field_name'];
$report_title1 = $_SESSION['report_title'];
$header_title1 = $_SESSION['header_title'];

$querySearch = "SELECT * FROM $table_name1 WHERE $field_name1 LIKE '%$searching_name1%' && $field_name1 != 'althaf' && branch_id = '$_SESSION[user_branch_id]' order by $field_name1";
$searchResult = $con->query($querySearch);


// echo $searching_name;
// echo "<br>";
// echo $table_name;
// echo "<br>";
// echo $field_name;
// echo "<br>";
// echo $report_title;
// echo "<br>";
// echo $header_title;

// Include FPDF library

require_once("../fpdf/fpdf.php");

// Create instance of FPDF
$pdf = new FPDF();
$pdf->AliasNbPages(); // Enable total page number
$pdf->AddPage(); // Add a page

// Company Header Section
$pdf->SetFont('Arial', 'B', 16);
$pdf->SetTextColor(0, 51, 102); // Dark blue
//$pdf->Cell(190, 10, $_SESSION['company_name']." ( ".$_SESSION['branch_name']." ) ", 0, 1, 'C'); // Company title
$pdf->Cell(190, 10, $_SESSION['branch_name'], 0, 1, 'C'); // Company title
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(50); // Gray text
$pdf->Cell(190, 8, $_SESSION['branch_address1']    .','.$_SESSION['branch_address2'], 0, 1, 'C');
$pdf->Cell(190, 8, $_SESSION['branch_address3']    .','.$_SESSION['branch_locality'], 0, 1, 'C');
$pdf->Cell(190, 8, $_SESSION['branch_city']        .','.$_SESSION['branch_pinCode'], 0, 1, 'C');
$pdf->Cell(190, 8,  $_SESSION['company_landline'].' | '.$_SESSION['branch_mobile'], 0, 1, 'C');
$pdf->Ln(10); // Line break

// Report Title Section
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetTextColor(0, 51, 102); // Dark blue
$pdf->Cell(190, 10, $report_title1, 0, 1, 'C');
$pdf->Ln(5);

// Subtitle with Date
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(50); // Gray text
$pdf->Cell(190, 10, 'Generated on: ' . date('d-m-Y'), 0, 1, 'C');
$pdf->Ln(5); // Line break

// Table Header
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetFillColor(200, 220, 255); // Light blue
$pdf->SetTextColor(0); // Black
$pdf->Cell(20, 10, 'S.No.', 1, 0, 'C', true);
$pdf->Cell(60, 10, $header_title1, 1, 0, 'C', true);
$pdf->Cell(40, 10, 'Created By', 1, 0, 'C', true);
$pdf->Cell(40, 10, 'Created Date', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'ID', 1, 1, 'C', true);
// Reset text color for rows
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(0);

// Check if there are any products
if ($searchResult && $searchResult->num_rows > 0) {
    $i=1;
    while ($data = $searchResult->fetch_assoc()) {
        // Add data rows
        $userName = "select user_name from user_master1 where id='$data[user_id]'";
        $resultUserName  = $con->query($userName)->fetch_assoc();
        $pdf->Cell(20, 10, $i++, 1, 0, 'C');
        $pdf->Cell(60, 10, $data[$field_name1], 1, 0, 'L');
        $pdf->Cell(40, 10, $resultUserName['user_name'], 1, 0, 'C');
        $pdf->Cell(40, 10, $data['created_date'], 1, 0, 'C');
        $pdf->Cell(30, 10, $data['id'], 1, 1, 'C');
        }
        $pdf->SetFont('Arial', 'I', 10);
        
        $pdf->SetTextColor(128); // Gray text
        $pdf->SetY(256);
        $pdf->Cell(0, 10, 'Page ' . $pdf->PageNo() . '/{nb}', 0, 1, 'C');
        $pdf->Cell(0, 10, 'Generated by '.$_SESSION['user_name'].' - '.$_SESSION['branch_name'], 0, 0, 'C');    
} else {
    // If no data is found
    $pdf->Cell(190, 10, 'No ' .$table_name1. ' found matching the search criteria.', 1, 1, 'C');
}





// Output the PDF
$pdf->Output();
ob_end_flush(); // End output buffering
exit;




// Set Footer font


// // Footer Section
// $pdf->SetY(10); // Position footer 3 cm from bottom
// $pdf->SetFont('Arial', 'I', 10);
// $pdf->SetTextColor(128); // Gray
// $pdf->Cell(0, 10, 'Page ' . $pdf->PageNo() . '/{nb}', 0, 1, 'C');
// $pdf->Cell(0, 10, 'Generated by '.$_SESSION['user_name'].' - '.$_SESSION['location_name'], 0, 0, 'C');