<?php
// Ensure no output before this script
ob_start(); // Start output buffering
include_once("../config/config.php");
include_once(DIR_URL . "/db/dbConnection.php");

$searching_name1 = $_SESSION['searching_name'] ?? ''; // Get field name from session or set as empty





$querySearch = "SELECT * FROM company WHERE company_name LIKE '%$searching_name1%'";
$searchResult = $con->query($querySearch);

// Include FPDF library
require_once("../fpdf/fpdf.php");

// Create instance of FPDF
$pdf = new FPDF('P', 'mm', [350,350]); // 'L' for Landscape, 'mm' for millimeters, 'A4' for paper size

$pdf->AliasNbPages(); // Enable total page number
$pdf->AddPage(); // Add a page

// Company Header Section
$pdf->SetFont('Arial', 'B', 16);
$pdf->SetTextColor(0, 51, 102); // Dark blue
//$pdf->Cell(0, 10, $_SESSION['company_name'], 0, 1, 'C'); // Company title
$pdf->Cell(0, 10, $_SESSION['branch_name'], 0, 1, 'C'); // Company title
$pdf->Ln(5);
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(50); // Gray text
$pdf->Cell(0, 8, $_SESSION['company_address1'] . ', ' . $_SESSION['company_address2'], 0, 1, 'C');
$pdf->Cell(0, 8, $_SESSION['company_address3'] . ', ' . $_SESSION['company_locality'], 0, 1, 'C');
$pdf->Cell(0, 8, $_SESSION['company_city'] . ', ' . $_SESSION['company_pincode'], 0, 1, 'C');
$pdf->Cell(0, 8, $_SESSION['company_landline'] . ' | ' . $_SESSION['company_mobile'], 0, 1, 'C');
$pdf->Ln(10); // Line break
// Footer Section



// Report Title Section
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetTextColor(0, 51, 102); // Dark blue
$pdf->Cell(0, 10, 'Companies Report', 0, 1, 'C');
$pdf->Ln(5);

// Subtitle with Date
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(50); // Gray text
$pdf->Cell(0, 10, ' Generated on: ' . date('d-m-Y').'  And  Generated by ' . $_SESSION['user_name'] . ' - ' . $_SESSION['user_location'], 0, 1, 'C');
$pdf->SetFont('Arial', 'I', 10);
$pdf->SetTextColor(160); // Gray text

$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . '/{nb}', 0, 1, 'R');
// $pdf->Cell(0, 5, 'Generated by ' . $_SESSION['user_name'] . ' - ' . $_SESSION['user_location'], 0, 0, 'C');
$pdf->Ln(5); // Line break

// Table Header
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(200, 220, 255); // Light blue
$pdf->SetTextColor(0); // Black

// Define column widths
$columns = [10, 50, 100, 100, 25]; // Adjusted column widths
$headers = ['S.No', 'Company Name', 'Address', 'Contacts', 'GST NO.'];

// Output headers
foreach ($headers as $i => $header) {
    $pdf->Cell($columns[$i], 10, $header, 1, 0, 'C', true);
}
$pdf->Ln();

// Reset text color for rows
$pdf->SetFont('Arial', '', 10);
$pdf->SetTextColor(0);

// Check if there are any suppliers
if ($searchResult && $searchResult->num_rows > 0) {
    $i=1;
    while ($data = $searchResult->fetch_assoc()) {
        

        $fullAddress = $data['address1'] . ', ' . $data['address2'] . ', ' . $data['address3'] . ', ' . $data['locality'] . ', ' . $data['city'] . ', ' . $data['pincode'] . ', ' . $data['state'];

        // Combine Landline, Mobile, and Email into a single line
        // $contactDetails = 'Landline: ' . $data['landline'] . ",\n Mobile: " . $data['mobile'] . ', Email: ' . $data['email'];
        $contactDetails = 'Landline: ' . $data['landline'] . "\nMobile: " . $data['mobile'] . "\nEmail: " . $data['email'];


        // Calculate height dynamically for wrapped text
        $lineHeight = 10; // Height of each line
        $maxLines = max(
            ceil($pdf->GetStringWidth($fullAddress) / ($columns[2] - 2)),
            1
        );
        $rowHeight = $lineHeight * $maxLines;

        // Add data rows
        $pdf->SetFont('Arial', 'B', 10); // Set font size to bold for ID
        $pdf->Cell($columns[0], $rowHeight, $i++, 1, 0, 'C');

        // Supplier Name
        $pdf->SetFont('Arial', '', 8); // Reset font size for other cells
        $pdf->Cell($columns[1], $rowHeight, $data['company_name'], 1, 0, 'L');

        // Address (MultiCell)
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->MultiCell($columns[2], $lineHeight, $fullAddress, 1, 'L');
        $pdf->SetXY($x + $columns[2], $y);

        // Contact Details (Single Line)
        $pdf->Cell($columns[3], $rowHeight, $contactDetails, 1, 0, 'L');

        // GST No.
        $pdf->Cell($columns[4], $rowHeight, $data['gst_no'], 1, 1, 'L');

        // Location ID
        
    }



} else {
    $pdf->Cell(array_sum($columns), 10, 'No Company found matching the search criteria.', 1, 1, 'C');
}



// Output the PDF
$pdf->Output();
ob_end_flush(); // End output buffering
exit;
?>
